spring:  
  application:
    name: discovery-service

server:  
  port: ${PORT:8761}
      
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  security:
    enabled: false